---
- name: My test playbook
  hosts: all
  become: true
  tasks:
  - name: install httpd for RedHat
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: httpd start for RedHat
    service:
      name: httpd--
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes

  - name: install apache2 for Debian
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: service apache2 start for Debian
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy index file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0666    
        

    
