---
- name: My test playbook
  hosts: all
  become: true
  tasks:
  - name: to create package httpd
    yum:
      name: httpd
      state: installed
  - name: service httpd start
    service:
      name: httpd
      state: started    
