---
- name: My test playbook
  hosts: all
  become: true
  tasks:
  - name: multiple users creation
    user:
      name: "{{ item }}"
      state: present  
    with_items:
      - Raj
      - Sai
      - Hari    
